AWSTemplateFormatVersion: "2010-09-09"
Description: "Dev Master Stack"

Parameters:
  SesDomainArns:
    Type: String
    Description: Comma Separated list of SES Domain Arns for sending Emails
    AllowedPattern:
      "arn:aws:ses:[a-z0-9-]+:\\d{12}:identity\\/[a-z0-9._-]+(,arn:aws:ses:[a-z0-9-]+:\\d{12}:identity\\/[a-z0-9._-]+)*"

Resources:
  LightrailAlertChannels:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../modules/alert-sns.yaml
  LightrailVPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../modules/vpc.yaml
      Parameters:
        BastionHostAuthorizedUsersGroup: Developers
        EnvironmentName: Dev
        NatInstanceType: t2.nano
        VPCUniqueNumber: 1
  LightrailECSCluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../modules/ecs-cluster.yaml
      Parameters:
        EnvironmentName: Dev
        ClusterName: lightrail-dev
        ClusterMinInstances: 1
        ClusterMaxInstances: 3
        ClusterInstanceType: t2.nano
        ClusterSSHKeyName: LightrailDevECS
        ClusterSecurityGroupIDs: !GetAtt LightrailVPC.Outputs.EcsClusterInstanceSecurityGroupId
        ClusterScaleUpRecurrence: "0 15 * * MON-FRI"
        ClusterScaleDownRecurrence: "0 3 * * TUE-SAT"
        VpcId: !GetAtt LightrailVPC.Outputs.VpcId
        VpcPublicSubnetIds: !GetAtt LightrailVPC.Outputs.PrivateSubnetIds
        Ec2SsmPolicyArn: !GetAtt SSM.Outputs.EC2PolicyArn
  LightrailRDS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../modules/rds.yaml
      Parameters:
        EnvironmentName: Dev
        RdsInstanceClass: db.m3.medium
        RdsInstanceAllocation: 100
        RdsMultiAZ: true
        RdsSnapshotId: ""
        VpcRDSSubnetIds: !GetAtt LightrailVPC.Outputs.RdsSubnetIds
        VpcHostedZoneId: !GetAtt LightrailVPC.Outputs.VpcHostedZoneId
        VpcSecurityGroupIds: !GetAtt LightrailVPC.Outputs.RdsSecurityGroupId
      Tags:
        -
          Key: Service
          Value: Services
  LightrailSecureConfig:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../modules/secure-bucket.yaml
      Parameters:
        EnvironmentName: Dev
  LightrailSecureDownload:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../modules/secure-bucket.yaml
      Parameters:
        EnvironmentName: Dev
  LightrailEventStream:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../modules/event-stream.yaml
      Parameters:
        EnvironmentName: Dev
  LightrailLogstash:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../modules/logstash.yaml
      Parameters:
        EnvironmentName: Dev
        NonEmergencyAlertsSnsArn: !GetAtt LightrailAlertChannels.Outputs.NonEmergencySNSArn
  LightrailDatadog:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../modules/datadog.yaml
      Parameters:
        EnvironmentName: Dev
  LightrailBatch:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../modules/batch-service.yaml
      Parameters:
        EnvironmentName: Dev
        ConfigurationBucketArn: !GetAtt LightrailSecureConfig.Outputs.BucketArn
        ConfigurationBucketKeyArn: !GetAtt LightrailSecureConfig.Outputs.EncryptionKeyArn
        SecureDownloadBucketArn: !GetAtt LightrailSecureDownload.Outputs.BucketArn
        SecureDownloadBucketKeyArn: !GetAtt LightrailSecureDownload.Outputs.EncryptionKeyArn
        SesDomainArns: !Ref SesDomainArns
        KinesisStreamArn: !GetAtt LightrailEventStream.Outputs.KinesisStreamArn
        RemoteECRRepositoryArn: ""

  SSM:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../modules/ssm.yaml
