AWSTemplateFormatVersion: "2010-09-09"
Description: Athena Bucket and permissions

Parameters:
  EnvironmentName:
    Type: String
    Description: The Name of the Environment
    AllowedValues:
      - Dev
      - Staging
      - Production

Resources:
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      Tags:
        -
          Key: Service
          Value: EventStream
  DataBucketEncryptionKey:
    Type: AWS::KMS::Key
    Properties:
      Description: !Sub "Lightrail ${EnvironmentName} Athena Accessible Data Lake Storage Key"
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              AWS:
                !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - "kms:*"
            Resource: "*"
  DataBucketEncryptionAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub "alias/${AWS::StackName}-AthenaDataLake"
      TargetKeyId: !Ref DataBucketEncryptionKey
#  BucketPolicy:
#    Type: AWS::S3::BucketPolicy
#    Properties:
#      Bucket: !Ref DataBucket
#      PolicyDocument:
#        Statement:
#          -  # For Security and consistency, don't allow putting any object not using the encryption key
#            Effect: Deny
#            Action:
#              - s3:PutObject*
#            Resource:
#              - !Sub "arn:aws:s3:::${DataBucket}/*"
#            Principal: "*"
#            Condition:
#              StringNotEquals:
#                "s3:x-amz-server-side-encryption-aws-kms-key-id": !GetAtt DataBucketEncryptionKey.Arn
Outputs:
  DataBucketName:
    Description: The Name of the Data Bucket
    Value: !Ref DataBucket
  EncryptionKeyArn:
    Description: The ARN of the Secure Configuration KMS Key
    Value: !GetAtt DataBucketEncryptionKey.Arn
