Description: Cards Search helper module

Parameters:
  EnvironmentName:
    Type: String
    Description: Please select your environment
    AllowedValues:
      - Dev
      - Staging
      - Production
  ProjectName:
    Type: String
    Description: The name of the project being built.  This name will be used on a number of resources.
  ConfigurationBucketName:
    Type: String
    Description: The Name of the Configuration Bucket
  ConfigurationBucketKeyArn:
    Type: String
    Description: The ARN of the Configuration Bucket Encryption Key
    AllowedPattern: arn:aws:kms:[a-z0-9-]+:\d{12}:key/[a-z0-9-]+
  DataDogConfigurationFileName:
    Type: String
    Description: The Name of the DataDog Configuration File in the Configuration Bucket
  JwtConfigurationFileName:
    Type: String
    Description: The Name of the JWT Configuration File in the Configuration Bucket
  RoleDefintionsConfigurationFileName:
    Type: String
    Description: The Name of the Role Defintions Configuration File in the Configuration Bucket
  GitHubOAuthToken:
    Type: String
    Description: GitHub oauth token.  This user must have admin access to the repo.
    Default: "****"
    NoEcho: true
  CodeBuildImageNodeSSH:
    Type: String
    Description: Name of the docker image to build from.
    Default: ""
  CiKeysAccessRoleArn:
    Type: String
    Description: ARN for the role that can access our CI SSH keys bucket.
    Default: ""
  CiKeysBucketName:
    Type: String
    Description: S3 bucket with our CI SSH keys.
    Default: ""

Mappings:
  Dev:
    us-west-2:
      GitHubBranch: dev-ci
      GitHubBranchDest: ""
      ElasticSearchInstanceCount: 2
      ElasticSearchInstanceType: t2.small.elasticsearch
      ElasticSearchMasterInstanceType: none
      RoleName: dev-CardsSearch-RestFunctionRole-1WFJDWKX4AFSD
      Endpoint: hon8eb7zgg.execute-api.us-west-2.amazonaws.com
  Staging:
    us-west-2:
      GitHubBranch: staging
      GitHubBranchDest: master
      ElasticSearchInstanceCount: 2
      ElasticSearchInstanceType: t2.small.elasticsearch
      ElasticSearchMasterInstanceType: none
      RoleName: staging-CardsSearch-RestFunctionRole-QB1BTL5IJBMS
      Endpoint: s7fqdm27c1.execute-api.us-west-2.amazonaws.com
  Production:
    us-west-2:
      GitHubBranch: master
      GitHubBranchDest: ""
      ElasticSearchInstanceCount: 2
      ElasticSearchInstanceType: t2.small.elasticsearch
      ElasticSearchMasterInstanceType: t2.small.elasticsearch
      RoleName: production-CardsSearch-RestFunctionRole-42IZL2PQ2ADC
      Endpoint: o0o62rx9nk.execute-api.us-west-2.amazonaws.com

Resources:
  CI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://raw.githubusercontent.com/Giftbit/giftbit-cards-search/2271464/infrastructure/ci.yaml
      Parameters:
        ProjectParameterOverrides: !Sub
          - >
            {
              "SecureConfigBucket": "${ConfigurationBucketName}",
              "SecureConfigKmsArn": "${ConfigurationBucketKeyArn}",
              "SecureConfigKeyJwt": "${JwtConfigurationFileName}",
              "SecureConfigKeyRoleDefinitions": "${RoleDefintionsConfigurationFileName}",
              "SecureConfigKeyDataDog": "${DataDogConfigurationFileName}",
              "KinesisStreamArn": "${LightrailEventStream.Outputs.KinesisStreamArn}",
              "MessageBucket": "${LightrailEventStream.Outputs.DataBucketName}",
              "MessageBucketKmsArn": "${LightrailEventStream.Outputs.EncryptionKeyArn}",
              "ElasticSearchInstanceCount": "${ElasticSearchInstanceCount}",
              "ElasticSearchInstanceType": "${ElasticSearchInstanceType}",
              "ElasticSearchMasterInstanceType": "${ElasticSearchMasterInstanceType}"
            }
          -
            ElasticSearchInstanceCount:
              !FindInMap [!Ref EnvironmentName, !Ref "AWS::Region", ElasticSearchInstanceCount]
            ElasticSearchInstanceType:
              !FindInMap [!Ref EnvironmentName, !Ref "AWS::Region", ElasticSearchInstanceType]
            ElasticSearchMasterInstanceType:
              !FindInMap [!Ref EnvironmentName, !Ref "AWS::Region", ElasticSearchMasterInstanceType]
        GitHubBranch: !FindInMap [!Ref EnvironmentName, !Ref "AWS::Region", GitHubBranch]
        GitHubBranchDest: !FindInMap [!Ref EnvironmentName, !Ref "AWS::Region", GitHubBranchDest]
        GitHubOAuthToken: !Ref GitHubOAuthToken
        CodeBuildImageNodeSSH: !REf CodeBuildImageNodeSSH
        CiKeysAccessRoleArn: !Ref CiKeysAccessRoleArn
        CiKeysBucketName: !Ref CiKeysBucketName
        ProjectName: !Sub "${AWS::StackName}-CardsSearch"
      Tags:
        -
          Key: Service
          Value: CardsSearch

Outputs:
  RoleName:
    Value: !FindInMap [!Ref EnvironmentName, !Ref "AWS::Region", RoleName]
  Endpoint:
    Value: !FindInMap [!Ref EnvironmentName, !Ref "AWS::Region", Endpoint]
