AWSTemplateFormatVersion: "2010-09-09"
Description: "Lightrail Certificates"

Parameters:
  BaseDomain:
    Type: String
    Description: The Base Domain Name that you want to use

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref BaseDomain
      SubjectAlternativeNames:
        - !Sub "www.${BaseDomain}"
        - !Sub "api.${BaseDomain}"
      DomainValidationOptions:
        -
          DomainName: !Sub "www.${BaseDomain}"
          ValidationDomain: !Ref BaseDomain
        -
          DomainName: !Sub "api.${BaseDomain}"
          ValidationDomain: !Ref BaseDomain

Outputs:
  CertificateArn:
    Description: The ARN of the certificate
    Value: !Ref Certificate
