AWSTemplateFormatVersion: "2010-09-09"
Description: "Lightrail Certificates"

Parameters:
  BaseDomain:
    Type: String
    Description: The Base Domain Name that you want to use

# SSL certs have to be in us-east-1.  We deploy this stack manually there to create
# the certificates.

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref BaseDomain
      SubjectAlternativeNames:
        - !Sub "www.${BaseDomain}"
        - !Sub "api.${BaseDomain}"
        - !Sub "embed.${BaseDomain}"
        - !Sub "blog.${BaseDomain}"
        - !Sub "try.${BaseDomain}"
      DomainValidationOptions:
        - DomainName: !Sub "www.${BaseDomain}"
          ValidationDomain: !Ref BaseDomain
        - DomainName: !Sub "api.${BaseDomain}"
          ValidationDomain: !Ref BaseDomain
        - DomainName: !Sub "embed.${BaseDomain}"
          ValidationDomain: !Ref BaseDomain
        - DomainName: !Sub "blog.${BaseDomain}"
          ValidationDomain: !Ref BaseDomain
        - DomainName: !Sub "try.${BaseDomain}"
          ValidationDomain: !Ref BaseDomain
      ValidationMethod: DNS

Outputs:
  CertificateArn:
    Description: The ARN of the certificate
    Value: !Ref Certificate
