AWSTemplateFormatVersion: "2010-09-09"
Description: "Lightrail CloudFront distribution configurations"

Parameters:
  EnvironmentName:
    Type: String
    Description: Please select your environment
    AllowedValues:
      - Dev
      - Staging
      - Production
  BaseDomainName:
    Type: String
    Description: Please enter the Base domain that you want the CloudFormation domains to be subdomains of
  PriceClass:
    Type: String
    Description: Please Select your Price Class
    Default: PriceClass_100
    AllowedValues:
      - PriceClass_All
      - PriceClass_100
      - PriceClass_200
  StaticContentLambdaVersionedArn:
    Type: String
    Description: Optional ARN *with version* of a Lambda@Edge function to run on the origin response of static content.  The Lambda must be in us-east-1.
    Default: ""
    AllowedPattern: ^(arn:aws:lambda:us-east-1:\d+:function:.*:.*)?$
  ViewerCertificateArn:
    Type: String
    Description: Arn of the AWS Certificate Manager cert for the CloudFront distribution (must be in us-east-1)
    Default: ""
  WebAclArn:
    Type: String
    Description: Optional ARN of the WAF Web ACL that will protect API CloudFront distributions.
    Default: ""
    AllowedPattern: ^(arn:aws:wafv2:us-east-1:\d+:global/webacl/ApiWebAcl/.*)?$
  EdhiEndpoint:
    Type: String
    Description: The domain that should handle the Edhi requests
  GutenbergEndpoint:
    Type: String
    Description: The domain that should handle the KVS requests
  KvsEndpoint:
    Type: String
    Description: The domain that should handle the KVS requests
  ReactEndpoint:
    Type: String
    Description: The domain that should handle the React app requests
    Default: ""
  RothschildEndpoint:
    Type: String
    Description: The domain that should handle Rothschild requests
  TurnkeyEndpoint:
    Type: String
    Description: The domain that should handle the Turnkey requests
  WebsiteEndpoint:
    Type: String
    Description: The domain that should handle the website requests
  WidgetsEndpoint:
    Type: String
    Description: The domain that should handle the Widgets requests
    Default: ""
  UserImageUploadAuthServiceEndpoint:
    Type: String
    Description: The domain that should handle the User Image Upload Authorization requests
  UserImageServingEndpoint:
    Type: String
    Description: The domain that should handle requests for a specific user images
  ConfigureAliases:
    Type: String
    AllowedValues:
      - "yes"
      - "no"
    Default: "yes"

Conditions:
  ShouldConfigureAliases: !Equals [!Ref ConfigureAliases, "yes"]  # This will be removed once we have the production account go live, but can be overridden quickly in cloudformation
  ViewerCertificateArnSet: !Not [!Equals [!Ref ViewerCertificateArn, ""]]
  ViewerCertificateArnNotSet: !Equals [!Ref ViewerCertificateArn, ""]
  WidgetsEndpointSet: !Not [!Equals [!Ref WidgetsEndpoint, ""]]

Resources:
  AppApiDistribution:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./cloudfront-api-distribution-template.yaml
      Parameters:
        # Default Distribution Endpoint
        DefaultEndpoint: !Ref WebsiteEndpoint
        # Distribution Specific Config
        AliasSubDomain: www
        # Distribution Specific Endpoints
        AppEndpoint: !Ref ReactEndpoint
        DocsEndpoint: !Ref ReactEndpoint
        UserImageServingEndpoint: !Ref UserImageServingEndpoint
        UserImageUploadAuthServiceEndpoint: !Ref UserImageUploadAuthServiceEndpoint
        ReferenceDocsEndpoint: !Ref WebsiteEndpoint
        # Common Endpoints
        EdhiEndpoint: !Ref EdhiEndpoint
        ErrorPagesEndpoint: !Ref WebsiteEndpoint
        KvsEndpoint: !Ref KvsEndpoint
        GutenbergEndpoint: !Ref GutenbergEndpoint
        RothschildEndpoint: !Ref RothschildEndpoint
        TurnkeyEndpoint: !Ref TurnkeyEndpoint
        # Common Distribution Configurations
        BaseDomainName: !Ref BaseDomainName
        EnvironmentName: !Ref EnvironmentName
        LoggingBucketDomainName: !GetAtt LoggingBucket.DomainName
        StaticContentLambdaVersionedArn: !Ref StaticContentLambdaVersionedArn
        ViewerCertificateArn: !Ref ViewerCertificateArn
        WebAclArn: !Ref WebAclArn
  ApiApiDistribution:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./cloudfront-api-distribution-template.yaml
      Parameters:
        # Default Distribution Endpoint
        DefaultEndpoint: !Sub "${ApiRedirectBucket}.s3-website-${AWS::Region}.amazonaws.com"
        # Distribution Specific Config
        AliasSubDomain: api
        # Common Endpoints
        EdhiEndpoint: !Ref EdhiEndpoint
        ErrorPagesEndpoint: !Ref WebsiteEndpoint
        KvsEndpoint: !Ref KvsEndpoint
        GutenbergEndpoint: !Ref GutenbergEndpoint
        RothschildEndpoint: !Ref RothschildEndpoint
        TurnkeyEndpoint: !Ref TurnkeyEndpoint
        # Common Distribution Configurations
        BaseDomainName: !Ref BaseDomainName
        EnvironmentName: !Ref EnvironmentName
        LoggingBucketDomainName: !GetAtt LoggingBucket.DomainName
        StaticContentLambdaVersionedArn: !Ref StaticContentLambdaVersionedArn
        ViewerCertificateArn: !Ref ViewerCertificateArn
        WebAclArn: !Ref WebAclArn
  EmbedApiDistribution:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./cloudfront-api-distribution-template.yaml
      Parameters:
        # Default Distribution Endpoint
        DefaultEndpoint: !Ref WidgetsEndpoint
        # Distribution Specific Config
        AliasSubDomain: embed
        # Common Endpoints
        EdhiEndpoint: !Ref EdhiEndpoint
        ErrorPagesEndpoint: !Ref WebsiteEndpoint
        KvsEndpoint: !Ref KvsEndpoint
        GutenbergEndpoint: !Ref GutenbergEndpoint
        RothschildEndpoint: !Ref RothschildEndpoint
        TurnkeyEndpoint: !Ref TurnkeyEndpoint
        # Common Distribution Configurations
        BaseDomainName: !Ref BaseDomainName
        EnvironmentName: !Ref EnvironmentName
        LoggingBucketDomainName: !GetAtt LoggingBucket.DomainName
        StaticContentLambdaVersionedArn: !Ref StaticContentLambdaVersionedArn
        ViewerCertificateArn: !Ref ViewerCertificateArn
        WebAclArn: !Ref WebAclArn
  ApiRedirectBucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
        RoutingRules:
          - RedirectRule:
              HostName: !Sub "www.${BaseDomainName}"
              ReplaceKeyWith: docs/
              Protocol: https
  AppZoneRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub "${BaseDomainName}."
      Name: !Sub "www.${BaseDomainName}."
      Type: A
      AliasTarget:
        DNSName: !GetAtt AppApiDistribution.Outputs.DomainName
        HostedZoneId: Z2FDTNDATAQYW2  # This is the Route53 HostedZoneId for CloudFront. See http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html
  ApiZoneRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub "${BaseDomainName}."
      Name: !Sub "api.${BaseDomainName}."
      Type: A
      AliasTarget:
        DNSName: !GetAtt ApiApiDistribution.Outputs.DomainName
        HostedZoneId: Z2FDTNDATAQYW2  # This is the Route53 HostedZoneId for CloudFront. See http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html
  EmbedZoneRecord:
    Type: AWS::Route53::RecordSet
    Condition: WidgetsEndpointSet
    Properties:
      HostedZoneName: !Sub "${BaseDomainName}."
      Name: !Sub "embed.${BaseDomainName}."
      Type: A
      AliasTarget:
        DNSName: !GetAtt EmbedApiDistribution.Outputs.DomainName
        HostedZoneId: Z2FDTNDATAQYW2  # This is the Route53 HostedZoneId for CloudFront. See http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html
  LoggingBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
  RedirectBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Sub "www.${BaseDomainName}"
          Protocol: https
  RedirectDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref BaseDomainName
        Enabled: true
        Comment: !Sub "Managed with CloudFormation Stack ${AWS::StackName}"
        PriceClass: !Ref PriceClass
        DefaultRootObject: index.html
        ViewerCertificate:
          AcmCertificateArn: !If [ViewerCertificateArnSet, !Ref ViewerCertificateArn, !Ref "AWS::NoValue"]
          CloudFrontDefaultCertificate: !If [ViewerCertificateArnNotSet, true, !Ref "AWS::NoValue"]
          SslSupportMethod: !If [ViewerCertificateArnSet, "sni-only", !Ref "AWS::NoValue"]
          MinimumProtocolVersion: TLSv1.2_2018
        Origins:
          - DomainName: !Sub "${RedirectBucket}.s3-website-${AWS::Region}.amazonaws.com"
            Id: RedirectOrigin
            CustomOriginConfig:
              OriginSSLProtocols:
                - TLSv1.2
              OriginProtocolPolicy: http-only
              HTTPSPort: 443
              HTTPPort: 80
        DefaultCacheBehavior:
          TargetOriginId: RedirectOrigin
          ViewerProtocolPolicy: allow-all
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          MinTTL: 0
          MaxTTL: 31536000
          DefaultTTL: 86400
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
  RedirectDomain:
    Type: AWS::Route53::RecordSet
    Properties:
      Comment: !Sub "Redirect Domain"
      HostedZoneName: !Sub "${BaseDomainName}."
      Name: !Sub "${BaseDomainName}."
      Type: A
      AliasTarget:
        DNSName: !GetAtt RedirectDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2  # This is the Route53 HostedZoneId for CloudFront. See http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html
  TrySubdomainRedirect:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./cloudfront-deprecated-subdomain-distribution.yaml
      Parameters:
        BaseDomainName: !Ref BaseDomainName
        SubdomainName: try
        ViewerCertificateArn: !Ref ViewerCertificateArn
        PriceClass: !Ref PriceClass
  BlogSubdomainRedirect:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./cloudfront-deprecated-subdomain-distribution.yaml
      Parameters:
        BaseDomainName: !Ref BaseDomainName
        SubdomainName: blog
        ViewerCertificateArn: !Ref ViewerCertificateArn
        PriceClass: !Ref PriceClass

Outputs:
  AppDomain:
    Description: The FQDN of the App
    Value: !Ref AppZoneRecord
  ApiDomain:
    Description: The FQDN of the Api
    Value: !Ref ApiZoneRecord
  AppDistributionDomain:
    Description: The Domain for the Lightrail CloudFront Distribution
    Value: !GetAtt AppApiDistribution.Outputs.DomainName
  ApiDistributionDomain:
    Description: The Domain for the Lightrail CloudFront Distribution
    Value: !GetAtt ApiApiDistribution.Outputs.DomainName
