AWSTemplateFormatVersion: "2010-09-09"
Description: "Lightrail DataDog"

Parameters:
  EnvironmentName:
    Type: String
    Description: The Name of the Environment
    AllowedValues:
      - Dev
      - Staging
      - Production
  AccountsToGrantECRFullAccess:
    Type: String
    Description: Comma separated list of AWS Account IDs to grant Read Access
    Default: ""
    AllowedPattern: (\d{12}(,\d{12})*)?

Conditions:
  ShouldCreateECRRepository: !Equals [!Ref EnvironmentName, Prod]
  ShouldConfigureECRAccess: !Not [!Equals [!Ref AccountsToGrantECRFullAccess, ""]]

Resources:
  # DataDog ECR Repository
  EcrRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryPolicyText: !If
        - ShouldConfigureECRAccess
        -
          Version: 2012-10-17
          Statement:
            -
              Sid: RepositoryAccess
              Effect: Allow
              Principal:
                AWS: !Split [",", !Ref AccountsToGrantECRFullAccess]
              Action:
                - ecr:GetDownloadUrlForLayer
                - ecr:BatchGetImage
                - ecr:BatchCheckLayerAvailability
                - ecr:PutImage
                - ecr:InitiateLayerUpload
                - ecr:UploadLayerPart
                - ecr:CompleteLayerUpload
                - ecr:DescribeRepositories
                - ecr:GetRepositoryPolicy
                - ecr:ListImages
        - !Ref AWS::NoValue
