Description: Edhi helper module

Parameters:
  EnvironmentName:
    Type: String
    Description: Please select your environment
    AllowedValues:
      - Dev
      - Staging
      - Production
  ProjectName:
    Type: String
    Description: The name of the project being built.  This name will be used on a number of resources.
  # SAM config
  LightrailDomain:
    Type: String
    Description: The domain of the Lightrail REST API
    AllowedPattern: (\w+\.)+\w{3}
  LightrailEmailDomain:
    Type: String
    Description: The lightrail email domain.
    Default: ""
  LightrailWebappDomain:
    Type: String
    Description: The domain of the Lightrail web app
    AllowedPattern: (\w+\.)+\w{3}
  SecureConfigBucket:
    Type: String
    Description: The Name of the Configuration Bucket
  SecureConfigKmsArn:
    Type: String
    Description: The ARN of the Configuration Bucket Encryption Key
    AllowedPattern: arn:aws:kms:[a-z0-9-]+:\d{12}:key/[a-z0-9-]+
  WebAclArn:
    Type: String
    Description: ARN of the WebACL protecting the REST API (updated to block deleted API keys)
    AllowedPattern: arn:aws:wafv2:us-east-1:\d+:global/webacl/.*/.*
  # CI config
  GitHubOAuthToken:
    Type: String
    Description: GitHub oauth token.  This user must have admin access to the repo.
    Default: "****"
    NoEcho: true
  CodeBuildImageNodeSSH:
    Type: String
    Description: Name of the docker image to build from.
    Default: ""
  CiKeysAccessRoleArn:
    Type: String
    Description: ARN for the role that can access our CI SSH keys bucket.
    Default: ""
  CiKeysBucketName:
    Type: String
    Description: S3 bucket with our CI SSH keys.
    Default: ""

Mappings:
  Dev:
    us-west-2:
      GitHubBranch: dev-ci
      GitHubBranchDest: ""
      RoleNames: dev-Edhi-RestFunctionRole-ZBKYVTBJZLW3,dev-Edhi-ApiKeyBlocklisterFunctionRole-1UC6X62QOX7R0
      Endpoint: ql9cnmujzl.execute-api.us-west-2.amazonaws.com
      SentryDsn: https://fb28f9ac76a84e879f7523cc07092369@o51938.ingest.sentry.io/239845
  Staging:
    us-west-2:
      GitHubBranch: staging
      GitHubBranchDest: master
      RoleNames: staging-Edhi-RestFunctionRole-MUB3HPT0IWQA,staging-Edhi-ApiKeyBlocklisterFunctionRole-15RF9HD1VY3V6
      Endpoint: jqpvyxgat0.execute-api.us-west-2.amazonaws.com
      SentryDsn: https://dad81b3b1b4e494e97069f17f4b9e33f@o51938.ingest.sentry.io/245144
  Production:
    us-west-2:
      GitHubBranch: master
      GitHubBranchDest: ""
      RoleNames: production-Edhi-RestFunctionRole-BC0X5SR4TIW,production-Edhi-ApiKeyBlocklisterFunctionRole-JZAQK1Y72UTY
      Endpoint: 1tjy5kf2t9.execute-api.us-west-2.amazonaws.com
      SentryDsn: https://b275b17e6ed948ae85b9de4fb0ab722b@o51938.ingest.sentry.io/245145

Resources:
  CI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://raw.githubusercontent.com/Giftbit/internal-edhi/9a312ef56cc8a19ad52f5308e4ee9c05fa632f45/infrastructure/ci.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        ProjectParameterOverrides: !Sub
          - >
            {
              "DeploymentPreferenceType": "Linear10PercentEvery1Minute",
              "LightrailDomain": "${LightrailDomain}",
              "LightrailEmailDomain": "${LightrailEmailDomain}",
              "LightrailWebappDomain": "${LightrailWebappDomain}",
              "SecureConfigBucket": "${SecureConfigBucket}",
              "SecureConfigKmsArn": "${SecureConfigKmsArn}",
              "SentryDsn": "${SentryDsn}",
              "WebAclArn": "${WebAclArn}"
            }
          - SentryDsn: !FindInMap [!Ref EnvironmentName, !Ref "AWS::Region", SentryDsn]
        GitHubOAuthToken: !Ref GitHubOAuthToken
        GitHubBranch: !FindInMap [!Ref EnvironmentName, !Ref "AWS::Region", GitHubBranch]
        GitHubBranchDest: !FindInMap [!Ref EnvironmentName, !Ref "AWS::Region", GitHubBranchDest]
        CiKeysAccessRoleArn: !Ref CiKeysAccessRoleArn
        CiKeysBucketName: !Ref CiKeysBucketName
        CodeBuildImageNodeSSH: !Ref CodeBuildImageNodeSSH
      Tags:
        - Key: Service
          Value: Edhi

Outputs:
  RoleNames:
    Value: !FindInMap [!Ref EnvironmentName, !Ref "AWS::Region", RoleNames]
  Endpoint:
    Value: !FindInMap [!Ref EnvironmentName, !Ref "AWS::Region", Endpoint]
