AWSTemplateFormatVersion: "2010-09-09"
Description: "Lightrail Services"

Parameters:
  EnvironmentName:
    Type: String
    Description: The Name of the Environment
    AllowedValues:
      - Dev
      - Staging
      - Production

Resources:
  KinesisStream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 1

      Tags:
        -
          Key: Service
          Value: EventStream

  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      Tags:
        -
          Key: Service
          Value: EventStream
  DataBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DataBucket
      PolicyDocument:
        Statement:
          -  # Since these objects are the last chance restore, make sure this never gets deleted
            Effect: Deny
            Action:
              - s3:DeleteBucket
              - s3:DeleteObject
              - s3:DeleteObjectVersion
            Resource:
              - !Sub "arn:aws:s3:::${DataBucket}"
              - !Sub "arn:aws:s3:::${DataBucket}/*"
            Principal: "*"

  FirehoseEncryptionKey:
    Type: AWS::KMS::Key
    Properties:
      Description: !Sub "Lightrail ${EnvironmentName} Data Lake Storage Key"
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              AWS:
                !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - "kms:*"
            Resource: "*"
  FirehoseEncryptionKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub "alias/${AWS::StackName}-DataLake"
      TargetKeyId: !Ref FirehoseEncryptionKey
  FirehoseRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - firehose.amazonaws.com
      Policies:
        -
          PolicyName: EncryptionAndBucketAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                # Granting Access to Decrypt seems weird, but Firehose says it needs it
                # http://docs.aws.amazon.com/firehose/latest/dev/controlling-access.html#using-iam-s3
                Effect: Allow
                Action:
                  - kms:Decrypt
                  - kms:GenerateDataKey
                Resource:
                  - !GetAtt FirehoseEncryptionKey.Arn
                Condition:
                  StringEquals:
                    kms:ViaService: !Sub "s3.${AWS::Region}.amazonaws.com"
                  StringLike:
                    kms:EncryptionContext:aws:s3:arn: !Sub "arn:aws:s3:::${DataBucket}/*"
              -
                Effect: Allow
                Action:
                  - s3:AbortMultipartUpload
                  - s3:GetBucketLocation
                  - s3:GetObject
                  - s3:ListObject
                  - s3:ListBucketMultipartUploads
                  - s3:PutObject
                Resource:
                  - !Sub "arn:aws:s3:::${DataBucket}"
                  - !Sub "arn:aws:s3:::${DataBucket}/*"
  FirehoseStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      S3DestinationConfiguration:
        RoleARN: !GetAtt FirehoseRole.Arn
        BucketARN: !Sub "arn:aws:s3:::${DataBucket}"
        CompressionFormat: GZIP
        EncryptionConfiguration:
          KMSEncryptionConfig:
            AWSKMSKeyARN: !GetAtt FirehoseEncryptionKey.Arn
        Prefix: ""
        BufferingHints:
          IntervalInSeconds: 300
          SizeInMBs: 5
  FirehoseRoleLogPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: WriteLogs
      Roles:
        - !Ref FirehoseRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource:
              # yamllint disable-line rule:line-length
              - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/kinesisfirehose/${FirehoseStream}:log-stream:*"

Outputs:
  KinesisStreamName:
    Description: The Name of the Kinesis Stream
    Value: !Ref KinesisStream
  KinesisStreamArn:
    Description: The ARN of the Kinesis Stream
    Value: !GetAtt KinesisStream.Arn
  DataBucketName:
    Description: The Name of the Data Bucket
    Value: !Ref DataBucket
  EncryptionKeyArn:
    Description: The ARN of the Secure Configuration KMS Key
    Value: !GetAtt FirehoseEncryptionKey.Arn
