AWSTemplateFormatVersion: "2010-09-09"
Description: "Lightrail Groups"

Parameters:
  EnvironmentName:
    Type: String
    Description: The Name of the Environment
    AllowedValues:
      - Dev
      - Staging
      - Production

Mappings:
  EnvNames:
    Lowercase:
      Dev: dev
      Staging: staging
      Production: production

Conditions:
  EnvironmentIsDevelopment: !Equals [!Ref EnvironmentName, Dev]

Resources:
  AllEmployees:
    Type: AWS::IAM::Group
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/IAMUserChangePassword
        - arn:aws:iam::aws:policy/IAMUserSSHKeys

  FrontEndDevelopersGroup:
    Type: AWS::IAM::Group
    Properties:
      ManagedPolicyArns:
        - !If
          - EnvironmentIsDevelopment
          - arn:aws:iam::aws:policy/PowerUserAccess
          - !Ref "AWS::NoValue"
        - arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSCodeBuildReadOnlyAccess
        - arn:aws:iam::aws:policy/CloudFrontReadOnlyAccess
      Policies:
        - PolicyName: NoCloudtrail
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Deny
                Action:
                  - "cloudtrail:*"
                Resource: "*"
        - PolicyName: NoAccountSecurityChanges
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Deny
                NotAction:
                  - cloudformation:Describe*
                  - cloudformation:List*
                Resource:
                  - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/AccountSecurity/*"
                  - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/AccountSecurity-*/*"
        - PolicyName: AwsHealthApisAndNotifications
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "health:*"
                Resource: "*"

  BackEndDevelopersGroup:
    Type: AWS::IAM::Group
    Properties:
      ManagedPolicyArns:
        - !If
          - EnvironmentIsDevelopment
          - arn:aws:iam::aws:policy/PowerUserAccess
          - !Ref "AWS::NoValue"
        - arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsReadOnlyAccess
        - arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSCodeBuildReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSCodePipelineApproverAccess
        - arn:aws:iam::aws:policy/AmazonRDSReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess
        - arn:aws:iam::aws:policy/CloudFrontReadOnlyAccess
      Policies:
        - !If
          - EnvironmentIsDevelopment
          - PolicyName: PassRoles
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                - Effect: Allow
                  Action:
                    - iam:GetRole
                    - iam:PassRole
                    - iam:ListRoles
                  Resource: "*"
          - !Ref AWS::NoValue
        - PolicyName: NoCloudtrail
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Deny
                Action:
                  - "cloudtrail:*"
                Resource: "*"
        - PolicyName: NoAccountSecurityChanges
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Deny
                NotAction:
                  - cloudformation:Describe*
                  - cloudformation:List*
                Resource:
                  - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/AccountSecurity/*"
                  - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/AccountSecurity-*/*"
        - PolicyName: AwsHealthApisAndNotifications
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "health:*"
                Resource: "*"
        - PolicyName: AwsLambdaReadOnlyAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - lambda:Get*
                  - lambda:List*
                Resource: "*"
        - PolicyName: AwsSupportAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - support:*
                Resource: "*"
        - PolicyName: RdsReboot
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - rds:CreateDbSnapshot
                  - rds:CreateDBClusterSnapshot
                  - rds:RebootDBInstance
                Resource: "*"
        - PolicyName: RdsPerformanceInsights
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: pi:*
                Resource: "arn:aws:pi:*:*:metrics/rds/*"

  MarkettingGroup:
    Type: AWS::IAM::Group

  BastionHostAccessGroup:
    Type: AWS::IAM::Group

  BasicCloudformationAccessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: BasicCloudformationAccess
      Groups:
        - !Ref MarkettingGroup
        - !Ref BackEndDevelopersGroup
        - !Ref FrontEndDevelopersGroup
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - cloudformation:ListExports
              - cloudformation:DescribeStacks
            Resource: "*"
          - Effect: Allow
            Action:
              - cloudformation:DescribeStackResource
            Resource:
              - !Sub
                - "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${EnvLowercase}/*"
                - EnvLowercase: !FindInMap [EnvNames, Lowercase, !Ref EnvironmentName]

  EC2ContainerServiceReadOnly:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: EC2ContainerServiceReadOnly
      Groups:
        - !Ref BackEndDevelopersGroup
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - ecs:Describe*
              - ecs:List*
            Resource: "*"

  BillingReadAccess:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: BillingReadAccess
      Groups:
        - !Ref AllEmployees
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - aws-portal:ViewBilling
              - aws-portal:ViewUsage
              - budgets:ViewBudget
            Resource: "*"

  ApiGatewayReadOnly:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: ApiGatewayReadOnly
      Groups:
        - !Ref BackEndDevelopersGroup
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - apigateway:GET
            Resource: "*"

  CodePipelineDeployRestartAccess:
    Type: AWS::IAM::Policy
    Properties:
      Groups:
        - !Ref BackEndDevelopersGroup
      PolicyName: CodePipelineDeployRestartAccess
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - codepipeline:RetryStageExecution
              - codepipeline:StartPipelineExecution
              - codepipeline:ListPipelineExecutions
            Resource: "*"

  CloudFormationChangeSetReadAccess:
    Type: AWS::IAM::Policy
    Properties:
      Groups:
        - !Ref BackEndDevelopersGroup
      PolicyName: CloudFormationChangeSetReadAccess
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - cloudformation:DescribeChangeSet
            Resource: "*"

  ElasticsearchServiceReadOnly:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: ElasticsearchServiceReadOnly
      Groups:
        - !Ref BackEndDevelopersGroup
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - es:Describe*
              - es:List*
            Resource: "*"

  ArshdeepV:
    Type: AWS::IAM::User
    Properties:
      UserName: arshdeep.v
      Groups:
        - !Ref AllEmployees
        - !Ref BackEndDevelopersGroup
        - !Ref FrontEndDevelopersGroup
  JamieT:
    Type: AWS::IAM::User
    Properties:
      UserName: jamie.t
      Groups:
        - !Ref AllEmployees
        - !Ref FrontEndDevelopersGroup
        - !Ref BackEndDevelopersGroup
  JeffG:
    Type: AWS::IAM::User
    Properties:
      UserName: jeff.g
      Groups:
        - !Ref AllEmployees
        - !Ref BackEndDevelopersGroup
        - !Ref BastionHostAccessGroup
        - !Ref FrontEndDevelopersGroup
  LeifB:
    Type: AWS::IAM::User
    Properties:
      UserName: leif.b
      Groups:
        - !Ref AllEmployees
  NickM:
    Type: AWS::IAM::User
    Properties:
      UserName: nick.m
      Groups:
        - !Ref AllEmployees
        - !Ref BackEndDevelopersGroup
        - !Ref FrontEndDevelopersGroup
  TanaJ:
    Type: AWS::IAM::User
    Properties:
      UserName: tana.j
      Groups:
        - !Ref AllEmployees
        - !Ref BackEndDevelopersGroup
        - !Ref BastionHostAccessGroup
        - !Ref FrontEndDevelopersGroup
  TimJ:
    Type: AWS::IAM::User
    Properties:
      UserName: tim.j
      Groups:
        - !Ref AllEmployees
        - !Ref BackEndDevelopersGroup
        - !Ref BastionHostAccessGroup
        - !Ref FrontEndDevelopersGroup

Outputs:

  BackEndDevelopersGroupName:
    Description: The Name of the Back End Developers Group
    Value: !Ref BackEndDevelopersGroup
  FrontEndDevelopersGroupName:
    Description: The Name of the Front End Developers Group
    Value: !Ref FrontEndDevelopersGroup
  MarkettingGroupName:
    Description: The Name of the Marketting Group
    Value: !Ref MarkettingGroup
  BastionHostAccessGroupName:
    Description: The Name of the Bastion Host Access Group
    Value: !Ref BastionHostAccessGroup
