Description: Gutenberg helper module

Parameters:
  EnvironmentName:
    Type: String
    Description: Please select your environment
    AllowedValues:
      - Dev
      - Staging
      - Production
  ProjectName:
    Type: String
    Description: The name of the project being built.  This name will be used on a number of resources.
  # SAM config
  LightrailDomain:
    Type: String
    Description: The domain of the Lightrail REST API
    AllowedPattern: (\w+\.)+\w+
  LightrailEventTopicArn:
    Type: String
    Description: Optional ARN of the SNS topic on Lightrail Events
    AllowedPattern: (arn:aws:sns:[a-zA-Z_0-9\-]+:\d{12}:[a-zA-Z_0-9+=,.@\-_/]+)?
    Default: ""
  SecureConfigBucket:
    Type: String
    Description: The Name of the Configuration Bucket
  SecureConfigKmsArn:
    Type: String
    Description: The ARN of the Configuration Bucket Encryption Key
    AllowedPattern: arn:aws:kms:[a-z0-9-]+:\d{12}:key/[a-z0-9-]+
  # CI config
  GitHubOAuthToken:
    Type: String
    Description: GitHub oauth token.  This user must have admin access to the repo.
    Default: "****"
    NoEcho: true
  CodeBuildImageNodeSSH:
    Type: String
    Description: Name of the docker image to build from.
    Default: ""
  CiKeysAccessRoleArn:
    Type: String
    Description: ARN for the role that can access our CI SSH keys bucket.
    Default: ""
  CiKeysBucketName:
    Type: String
    Description: S3 bucket with our CI SSH keys.
    Default: ""

Mappings:
  Dev:
    us-west-2:
      GitHubBranch: dev-ci
      GitHubBranchDest: ""
      RoleNames: ''#dev-Gutenberg-RestFunctionRole-XXX,dev-Gutenberg-EventsFunctionRole-XXX
      Endpoint: ''#xxx.execute-api.us-west-2.amazonaws.com
      SentryDsn: ''#https://xxx@xxx.ingest.sentry.io/xxx
  Staging:
    us-west-2:
      GitHubBranch: staging
      GitHubBranchDest: master
      RoleNames: ''#staging-Gutenberg-RestFunctionRole-XXX,staging-Gutenberg-EventsFunctionRole-XXX
      Endpoint: ''#xxx.execute-api.us-west-2.amazonaws.com
      SentryDsn: ''#https://xxx@xxx.ingest.sentry.io/xxx
  Production:
    us-west-2:
      GitHubBranch: master
      GitHubBranchDest: ""
      RoleNames: ''#production-Gutenberg-RestFunctionRole-XXX,production-Gutenberg-EventsFunctionRole-XXX
      Endpoint: ''#xxx.execute-api.us-west-2.amazonaws.com
      SentryDsn: ''#https://xxx@xxx.ingest.sentry.io/xxx

Resources:
  CI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://raw.githubusercontent.com/Giftbit/internal-gutenberg/bb0e1ae2f448fee8f2d8fb628cf068de36d7cce2/infrastructure/ci.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        ProjectParameterOverrides: !Sub
          - >
            {
                "DeploymentPreferenceType": "Linear10PercentEvery1Minute",
                "LightrailDomain": "${LightrailDomain}",
                "LightrailEventTopicArn": "${LightrailEventTopicArn}",
                "SecureConfigBucket": "${SecureConfigBucket}",
                "SecureConfigKmsArn": "${SecureConfigKmsArn}",
                "SentryDsn": "${SentryDsn}"
            }
          - SentryDsn: !FindInMap [!Ref EnvironmentName, !Ref "AWS::Region", SentryDsn]
        LightrailEventTopicArn: !Ref LightrailEventTopicArn
        GitHubOAuthToken: !Ref GitHubOAuthToken
        GitHubBranch: !FindInMap [!Ref EnvironmentName, !Ref "AWS::Region", GitHubBranch]
        GitHubBranchDest: !FindInMap [!Ref EnvironmentName, !Ref "AWS::Region", GitHubBranchDest]
        CiKeysAccessRoleArn: !Ref CiKeysAccessRoleArn
        CiKeysBucketName: !Ref CiKeysBucketName
        CodeBuildImageNodeSSH: !Ref CodeBuildImageNodeSSH
      Tags:
      - Key: Service
        Value: Gutenberg

Outputs:
  RoleNames:
    Value: !FindInMap [!Ref EnvironmentName, !Ref "AWS::Region", RoleNames]
  Endpoint:
    Value: !FindInMap [!Ref EnvironmentName, !Ref "AWS::Region", Endpoint]

