Description: Gutenberg helper module

Parameters:
  EnvironmentName:
    Type: String
    Description: Please select your environment
    AllowedValues:
      - Dev
      - Staging
      - Production
  ProjectName:
    Type: String
    Description: The name of the project being built.  This name will be used on a number of resources.
  # SAM config
  LightrailDomain:
    Type: String
    Description: The domain of the Lightrail REST API
    AllowedPattern: (\w+\.)+\w{3}
  LightrailEventTopicArn:
    Type: String
    Description: Optional ARN of the SNS topic on Lightrail Events
    AllowedPattern: (arn:aws:sns:[a-zA-Z_0-9\-]+:\d{12}:[a-zA-Z_0-9+=,.@\-_/]+)?
    Default: ""
  SecureConfigBucket:
    Type: String
    Description: The Name of the Configuration Bucket
  SecureConfigKmsArn:
    Type: String
    Description: The ARN of the Configuration Bucket Encryption Key
    AllowedPattern: arn:aws:kms:[a-z0-9-]+:\d{12}:key/[a-z0-9-]+
  # CI config
  GitHubOAuthToken:
    Type: String
    Description: GitHub oauth token.  This user must have admin access to the repo.
    Default: "****"
    NoEcho: true
  CodeBuildImageNodeSSH:
    Type: String
    Description: Name of the docker image to build from.
    Default: ""
  CiKeysAccessRoleArn:
    Type: String
    Description: ARN for the role that can access our CI SSH keys bucket.
    Default: ""
  CiKeysBucketName:
    Type: String
    Description: S3 bucket with our CI SSH keys.
    Default: ""

Mappings:
  Dev:
    us-west-2:
      GitHubBranch: dev-ci
      GitHubBranchDest: ""
      RoleNames: dev-Gutenberg-RestFunctionRole-1M3F24PK6D0C3,dev-Gutenberg-EventsFunctionRole-RPXIWDPYOVP5
      Endpoint: 5t4x5i9e7e.execute-api.us-west-2.amazonaws.com
      SentryDsn: https://fb28f9ac76a84e879f7523cc07092369@o51938.ingest.sentry.io/239845
  Staging:
    us-west-2:
      GitHubBranch: staging
      GitHubBranchDest: master
      RoleNames: staging-Gutenberg-RestFunctionRole-172FW1RJ36QKW,staging-Gutenberg-EventsFunctionRole-EI36SO42J4RI
      Endpoint: d267yqujga.execute-api.us-west-2.amazonaws.com
      SentryDsn: https://dad81b3b1b4e494e97069f17f4b9e33f@o51938.ingest.sentry.io/245144
  Production:
    us-west-2:
      GitHubBranch: master
      GitHubBranchDest: ""
      RoleNames: production-Gutenberg-RestFunctionRole-1P7K16D960LG9,production-Gutenberg-EventsFunctionRole-98WOGTSGGV4F
      Endpoint: hxoiqowlci.execute-api.us-west-2.amazonaws.com
      SentryDsn: https://b275b17e6ed948ae85b9de4fb0ab722b@o51938.ingest.sentry.io/245145

Resources:
  CI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://raw.githubusercontent.com/Giftbit/internal-gutenberg/94bf3cfd7aa0f2ee89c8b014486371103aa7fc02/infrastructure/ci.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        ProjectParameterOverrides: !Sub
          - >
            {
                "LightrailDomain": "${LightrailDomain}",
                "LightrailEventTopicArn": "${LightrailEventTopicArn}",
                "SecureConfigBucket": "${SecureConfigBucket}",
                "SecureConfigKmsArn": "${SecureConfigKmsArn}",
                "SentryDsn": "${SentryDsn}"
            }
          - SentryDsn: !FindInMap [!Ref EnvironmentName, !Ref "AWS::Region", SentryDsn]
        LightrailEventTopicArn: !Ref LightrailEventTopicArn
        GitHubOAuthToken: !Ref GitHubOAuthToken
        GitHubBranch: !FindInMap [!Ref EnvironmentName, !Ref "AWS::Region", GitHubBranch]
        GitHubBranchDest: !FindInMap [!Ref EnvironmentName, !Ref "AWS::Region", GitHubBranchDest]
        CiKeysAccessRoleArn: !Ref CiKeysAccessRoleArn
        CiKeysBucketName: !Ref CiKeysBucketName
        CodeBuildImageNodeSSH: !Ref CodeBuildImageNodeSSH
      Tags:
      - Key: Service
        Value: Gutenberg

Outputs:
  RoleNames:
    Value: !FindInMap [!Ref EnvironmentName, !Ref "AWS::Region", RoleNames]
  Endpoint:
    Value: !FindInMap [!Ref EnvironmentName, !Ref "AWS::Region", Endpoint]

