Description: KVS helper module

Parameters:
  EnvironmentName:
    Type: String
    Description: Please select your environment
    AllowedValues:
      - Dev
      - Staging
      - Production
  ProjectName:
    Type: String
    Description: The name of the project being built.  This name will be used on a number of resources.
  # SAM config
  LightrailDomain:
    Type: String
    Description: The domain of the Lightrail REST API
    AllowedPattern: (\w+\.)+\w{3}
  PathToMerchantSharedSecret:
    Type: String
    Description: Path to merchant shared jwt secret
  SecureConfigBucket:
    Type: String
    Description: The Name of the Configuration Bucket
  SecureConfigKmsArn:
    Type: String
    Description: The ARN of the Configuration Bucket Encryption Key
    AllowedPattern: arn:aws:kms:[a-z0-9-]+:\d{12}:key/[a-z0-9-]+
  SecureConfigKeyAssumeStorageScopeToken:
    Type: String
    Description: Name of the Assume Auth token in S3 that can be used to access merchant secret key in KVS
  SecureConfigKeyJwt:
    Type: String
    Description: The Name of the JWT Configuration File in the Configuration Bucket
  SecureConfigKeyRoleDefinitions:
    Type: String
    Description: The Name of the Role Defintions Configuration File in the Configuration Bucket
  # CI config
  GitHubOAuthToken:
    Type: String
    Description: GitHub oauth token.  This user must have admin access to the repo.
    Default: "****"
    NoEcho: true
  CodeBuildImageNodeSSH:
    Type: String
    Description: Name of the docker image to build from.
    Default: ""
  CiKeysAccessRoleArn:
    Type: String
    Description: ARN for the role that can access our CI SSH keys bucket.
    Default: ""
  CiKeysBucketName:
    Type: String
    Description: S3 bucket with our CI SSH keys.
    Default: ""

Mappings:
  Dev:
    us-west-2:
      GitHubBranch: dev-ci
      GitHubBranchDest: ""
      Capacity: low
      RoleName: dev-Kvs-KvsFunctionRole-RLFP80MZ8Z16
      Endpoint: wowqnrwyy0.execute-api.us-west-2.amazonaws.com
      SentryDsn: https://fb28f9ac76a84e879f7523cc07092369@o51938.ingest.sentry.io/239845
  Staging:
    us-west-2:
      GitHubBranch: staging
      GitHubBranchDest: master
      Capacity: low
      RoleName: staging-Kvs-KvsFunctionRole-16TX23DYH1DQ
      Endpoint: 1tnp8xblpd.execute-api.us-west-2.amazonaws.com
      SentryDsn: https://dad81b3b1b4e494e97069f17f4b9e33f@o51938.ingest.sentry.io/245144
  Production:
    us-west-2:
      GitHubBranch: master
      GitHubBranchDest: ""
      Capacity: high
      RoleName: production-Kvs-KvsFunctionRole-35C9CNH786LQ
      Endpoint: hl0fjfzg5b.execute-api.us-west-2.amazonaws.com
      SentryDsn: https://b275b17e6ed948ae85b9de4fb0ab722b@o51938.ingest.sentry.io/245145

Resources:
  EncryptionKey:
    Type: AWS::KMS::Key
    Properties:
      Description: !Sub "${AWS::StackName} stored item encryption key"
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - kms:*
            Resource: "*"
  EncryptionKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub "alias/${AWS::StackName}-EncryptionKey"
      TargetKeyId: !Ref EncryptionKey
  CI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://raw.githubusercontent.com/Giftbit/internal-kvs/e9f244dda730837e2a463a66e5be442d38594e1f/infrastructure/ci.yaml
      Parameters:
        ProjectParameterOverrides: !Sub
          - >
            {
              "Capacity": "${Capacity}",
              "DeploymentPreferenceType": "Linear10PercentEvery1Minute",
              "LightrailDomain": "${LightrailDomain}",
              "PathToMerchantSharedSecret": "${PathToMerchantSharedSecret}",
              "SecureConfigBucket": "${SecureConfigBucket}",
              "SecureConfigKmsArn": "${SecureConfigKmsArn}",
              "SecureConfigKeyAssumeStorageScopeToken": "${SecureConfigKeyAssumeStorageScopeToken}",
              "SecureConfigKeyJwt": "${SecureConfigKeyJwt}",
              "SecureConfigKeyRoleDefinitions": "${SecureConfigKeyRoleDefinitions}",
              "SentryDsn": "${SentryDsn}",
              "StoredItemEncryptionKeyId": "${EncryptionKey}"
            }
          - Capacity: !FindInMap [!Ref EnvironmentName, !Ref "AWS::Region", Capacity]
            SentryDsn: !FindInMap [!Ref EnvironmentName, !Ref "AWS::Region", SentryDsn]
        GitHubBranch: !FindInMap [!Ref EnvironmentName, !Ref "AWS::Region", GitHubBranch]
        GitHubBranchDest: !FindInMap [!Ref EnvironmentName, !Ref "AWS::Region", GitHubBranchDest]
        GitHubOAuthToken: !Ref GitHubOAuthToken
        CodeBuildImageNodeSSH: !Ref CodeBuildImageNodeSSH
        CiKeysAccessRoleArn: !Ref CiKeysAccessRoleArn
        CiKeysBucketName: !Ref CiKeysBucketName
        ProjectName: !Ref ProjectName
      Tags:
        - Key: Service
          Value: KVS

Outputs:
  RoleName:
    Value: !FindInMap [!Ref EnvironmentName, !Ref "AWS::Region", RoleName]
  Endpoint:
    Value: !FindInMap [!Ref EnvironmentName, !Ref "AWS::Region", Endpoint]
