AWSTemplateFormatVersion: "2010-09-09"
Description: Lightrail Basic SSM Setup

Parameters:
  InstanceLogBucketName:
    Type: String
    Default: giftbit-instance-logs
    Description: Enter the S3 bucket you would like the instance logs to go
    AllowedPattern: "[a-z0-9.-]+"
  InstanceLogEncryptionKeyArn:
    Type: String
    Default: arn:aws:kms:us-west-2:131941013619:key/88612fbb-89ac-494b-8126-6446bc5d0038
    Description: Enter the KMS Key Arn you should like to use for encrypting your instance logs
    AllowedPattern: arn:aws:kms:[a-z0-9-]+:\d{12}:key/[a-z0-9-]+

Resources:
  # SSM Bucket
  SSMBucket:
    Type: AWS::S3::Bucket

  # EC2 Policy for SSM Basic Access
  EC2PolicyForSSM:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: A Common Policy for granting basic SSM access for EC2 managed instances
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - ssm:DescribeAssociation
              - ssm:GetDocument
              - ssm:ListAssociations
              - ssm:ListInstanceAssociations
              - ssm:PutInventory
              - ssm:UpdateAssocationStatus
              - ssm:UpdateInstanceAssociationStatus
              - ssm:UpdateInstanceInformation
            Resource: "*"
          - Effect: Allow
            Action:
              - ec2messages:AcknowledgeMessage
              - ec2messages:DeleteMessage
              - ec2messages:FailMessage
              - ec2messages:GetEndpoint
              - ec2messages:GetMessages
              - ec2messages:SendReply
            Resource: "*"
          - Effect: Allow
            Action:
              - cloudwatch:PutMetricData
            Resource: "*"
          - Effect: Allow
            Action:
              - ec2:DescribeInstanceStatus
            Resource: "*"
          - Effect: Allow
            Action:
              - ds:CreateComputer
              - ds:DescribeDirectories
            Resource: "*"
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:DescribeLogGroups
              - logs:DescribeLogStreams
              - logs:PutLogEvents
            Resource: "*"
          - Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:AbortMultipartUpload
              - s3:ListMultipartUploadParts
              - s3:ListBucketMultipartUploads
            Resource:
              - !Sub "arn:aws:s3:::${SSMBucket}"
              - !Sub "arn:aws:s3:::${SSMBucket}/*"

  # Instance Log Centralization
  SynchronizeLogsDocument:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Command
      Content:
        schemaVersion: "1.2"
        description: Synchronizes the instance logs with the central logging location.
        runtimeConfig:
          aws:runShellScript:
            properties:
              runCommand:
                - sudo yum list installed aws-cli || sudo yum install -y aws-cli
                - |
                  role_id=$(aws iam get-role \
                    --role-name $(curl 169.254.169.254/latest/meta-data/iam/security-credentials/) \
                    --query Role.RoleId \
                    --output text)
                - instance_id=$(curl 169.254.169.254/latest/meta-data/instance-id)
                - sudo aws configure set default.s3.multipart_threshold 5GB
                - !Sub |
                  sudo aws s3 sync \
                    --acl bucket-owner-full-control \
                    --sse aws:kms \
                    --sse-kms-key-id ${InstanceLogEncryptionKeyArn} \
                    /var/log s3://${InstanceLogBucketName}/$role_id:$instance_id
              timeout: 300
  SynchronizeLogsAssociation:
    Type: AWS::SSM::Association
    Properties:
      Name:
        !Ref SynchronizeLogsDocument
      ScheduleExpression: "cron(0 0 0/1 1/1 * ? *)"
      Targets:
        - Key: !Sub "tag:CentralizeLogs"
          Values:
            - true

Outputs:
  SSMBucketName:
    Description: The name of the SSM Bucket
    Value: !Ref SSMBucket
  EC2PolicyArn:
    Description: The Arn for the policy EC2 instances should use for SSM
    Value: !Ref EC2PolicyForSSM
