Description: Turnkey helper module

Parameters:
  EnvironmentName:
    Type: String
    Description: Please select your environment
    AllowedValues:
      - Dev
      - Staging
      - Production
  ProjectName:
    Type: String
    Description: The name of the project being built.  This name will be used on a number of resources.
  LightrailDomain:
    Type: String
    Description: The domain of the Lightrail REST API
    AllowedPattern: (\w+\.)+\w{3}
  LightrailWebappDomain:
    Type: String
    Description: The domain of the Lightrail web app
    AllowedPattern: (\w+\.)+\w{3}
  SecureConfigBucket:
    Type: String
    Description: The Name of the Configuration Bucket
  SecureConfigKmsArn:
    Type: String
    Description: The ARN of the Configuration Bucket Encryption Key
    AllowedPattern: arn:aws:kms:[a-z0-9-]+:\d{12}:key/[a-z0-9-]+
  SecureConfigKeyJwt:
    Type: String
    Description: The Name of the JWT Configuration File in the Configuration Bucket
  SecureConfigKeyRoleDefinitions:
    Type: String
    Description: The Name of the Role Defintions Configuration File in the Configuration Bucket
  SecureConfigKeyStripe:
    Type: String
    Description: Key of the Stripe Connect secure config object in S3
  GitHubOAuthToken:
    Type: String
    Description: GitHub oauth token.  This user must have admin access to the repo.
    Default: "****"
    NoEcho: true
  EmailDomainName:
    Type: String
    Description: The lightrail email domain.
    Default: ""
  SecureConfigKeyAssumeGiftcardPurchaseToken:
    Type: String
    Description: Name of the Assume Auth token in S3 that can has the scopes required for the giftcard purchase lambda
  SecureConfigKeyAssumeStorageScopeToken:
    Type: String
    Description: Name of the Assume Auth token in S3 that can be used to access merchant secret key in KVS
  SecureConfigKeyDataDog:
    Type: String
    Description: Key of the DataDog API key secure config object in S3
  SecureConfigKeySentry:
    Type: String
    Description: Key of the Sentry API key secure config object in S3
  PathToMerchantSharedSecret:
    Type: String
    Description: Path to merchant shared jwt secret
  CodeBuildImageNodeSSH:
    Type: String
    Description: Name of the docker image to build from.
    Default: ""
  CiKeysAccessRoleArn:
    Type: String
    Description: ARN for the role that can access our CI SSH keys bucket.
    Default: ""
  CiKeysBucketName:
    Type: String
    Description: S3 bucket with our CI SSH keys.
    Default: ""

Mappings:
  Dev:
    us-west-2:
      GitHubBranch: dev-ci
      GitHubBranchDest: ""
      RoleNames: dev-Turnkey-GiftcardPurchaseFunctionRole-1KGBM93LPXQFP,dev-Turnkey-StripeFunctionRole-1G73BZDEQRT90
      Endpoint: vjn3uqm8ok.execute-api.us-west-2.amazonaws.com
  Staging:
    us-west-2:
      GitHubBranch: staging
      GitHubBranchDest: master
      RoleNames: staging-Turnkey-GiftcardPurchaseFunctionRole-6OE7SS30H6TU,staging-Turnkey-StripeFunctionRole-V0W37G8KYYD3
      Endpoint: tk1tioiyz5.execute-api.us-west-2.amazonaws.com
  Production:
    us-west-2:
      GitHubBranch: master
      GitHubBranchDest: ""
      RoleNames: production-Turnkey-GiftcardPurchaseFunctionRole-1VO6BCQNGZKOZ,production-Turnkey-StripeFunctionRole-107HU60YD7SP7
      Endpoint: 13shovrsob.execute-api.us-west-2.amazonaws.com

Resources:
  CI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://raw.githubusercontent.com/Giftbit/internal-turnkey/0bc5e6befde630e5aef7fde3565dba9847698fb0/infrastructure/ci.yaml
      Parameters:
        ProjectParameterOverrides: !Sub >
            {
              "LightrailDomain": "${LightrailDomain}",
              "EmailDomainName": "${EmailDomainName}",
              "LightrailWebappDomain": "${LightrailWebappDomain}",
              "PathToMerchantSharedSecret: "${PathToMerchantSharedSecret}",
              "SecureConfigBucket": "${SecureConfigBucket}",
              "SecureConfigKmsArn": "${SecureConfigKmsArn}",
              "SecureConfigKeyJwt": "${SecureConfigKeyJwt}",
              "SecureConfigKeyRoleDefinitions": "${SecureConfigKeyRoleDefinitions}",
              "SecureConfigKeyStripe": "${SecureConfigKeyStripe}",
              "SecureConfigKeyAssumeGiftcardPurchaseToken": "${SecureConfigKeyAssumeGiftcardPurchaseToken}",
              "SecureConfigKeyAssumeStorageScopeToken": "${SecureConfigKeyAssumeStorageScopeToken}",
              "SecureConfigKeyDataDog": "${SecureConfigKeyDataDog}",
              "SecureConfigKeySentry": "${SecureConfigKeySentry}"
            }
        GitHubBranch: !FindInMap [!Ref EnvironmentName, !Ref "AWS::Region", GitHubBranch]
        GitHubBranchDest: !FindInMap [!Ref EnvironmentName, !Ref "AWS::Region", GitHubBranchDest]
        GitHubOAuthToken: !Ref GitHubOAuthToken
        CodeBuildImageNodeSSH: !Ref CodeBuildImageNodeSSH
        CiKeysAccessRoleArn: !Ref CiKeysAccessRoleArn
        CiKeysBucketName: !Ref CiKeysBucketName
        ProjectName: !Ref ProjectName
      Tags:
        - Key: Service
          Value: Turnkey

Outputs:
  RoleNames:
    Value: !FindInMap [!Ref EnvironmentName, !Ref "AWS::Region", RoleNames]
  Endpoint:
    Value: !FindInMap [!Ref EnvironmentName, !Ref "AWS::Region", Endpoint]
