AWSTemplateFormatVersion: 2010-09-09
Description: Logo Upload Helper Module

Parameters:
  EnvironmentName:
    Type: String
    Description: Please select your environment
    AllowedValues:
      - Dev
      - Staging
      - Production
  ProjectName:
    Type: String
    Description: The name of the project being built.  This name will be used on a number of resources.
  SecureConfigBucket:
    Type: String
    Description: The Name of the Configuration Bucket
  SecureConfigKmsArn:
    Type: String
    Description: The ARN of the Configuration Bucket Encryption Key
    AllowedPattern: arn:aws:kms:[a-z0-9-]+:\d{12}:key/[a-z0-9-]+
  SecureConfigKeyJwt:
    Type: String
    Description: The Name of the JWT Configuration File in the Configuration Bucket
  SecureConfigKeyRoleDefinitions:
    Type: String
    Description: The Name of the Role Defintions Configuration File in the Configuration Bucket
  GitHubOAuthToken:
    Type: String
    Description: GitHub oauth token.  This user must have admin access to the repo.
    Default: "****"
    NoEcho: true
  CodeBuildImageNodeSSH:
    Type: String
    Description: Name of the docker image to build from.
    Default: ""
  CiKeysAccessRoleArn:
    Type: String
    Description: ARN for the role that can access our CI SSH keys bucket.
    Default: ""
  CiKeysBucketName:
    Type: String
    Description: S3 bucket with our CI SSH keys.
    Default: ""
  WebsiteDomainUrl:
    Type: String
    Description: The Scheme and Domain that will serve the logos
    AllowedPattern: https:\/\/[^/]+

Mappings:
  Dev:
    us-west-2:
      GitHubBranch: dev-ci
      GitHubBranchDest: ""
      RoleName: dev-UserImageUpload-UserImageUploadAuthorizerFunct-1A6P5R057WL3S
      ServiceEndpoint: vqoidwy5sh.execute-api.us-west-2.amazonaws.com
      BucketEndpoint: dev-userimageupload-userimagebucket-20d0e1r9jz38.s3-website-us-west-2.amazonaws.com
  Staging:
    us-west-2:
      GitHubBranch: staging
      GitHubBranchDest: master
      RoleName: ""
      ServiceEndpoint: ""
      BucketEndpoint: ""
  Production:
    us-west-2:
      GitHubBranch: master
      GitHubBranchDest: ""
      RoleName: ""
      ServiceEndpoint: ""
      BucketEndpoint: ""

Resources:
  CI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://raw.githubusercontent.com/Giftbit/lightrail-user-image-upload/01bba0d93be129ae8630285642830d189279dc74/infrastructure/ci.yaml
      Parameters:
        ProjectParameterOverrides: !Sub >
          {
            "SecureConfigBucket": "${SecureConfigBucket}",
            "SecureConfigKmsArn": "${SecureConfigKmsArn}",
            "SecureConfigKeyJwt": "${SecureConfigKeyJwt}",
            "SecureConfigKeyRoleDefinitions": "${SecureConfigKeyRoleDefinitions}",
            "WebsiteDomainUrl": "${WebsiteDomainUrl}",
            "UserImagePath": "v1/userImages"
          }
        GitHubBranch: !FindInMap [!Ref EnvironmentName, !Ref "AWS::Region", GitHubBranch]
        GitHubBranchDest: !FindInMap [!Ref EnvironmentName, !Ref "AWS::Region", GitHubBranchDest]
        GitHubOAuthToken: !Ref GitHubOAuthToken
        CodeBuildImageNodeSSH: !Ref CodeBuildImageNodeSSH
        CiKeysAccessRoleArn: !Ref CiKeysAccessRoleArn
        CiKeysBucketName: !Ref CiKeysBucketName
        ProjectName: !Ref ProjectName
      Tags:
        -
          Key: Service
          Value: UserImageUpload

Outputs:
  RoleName:
    Value: !FindInMap [!Ref EnvironmentName, !Ref "AWS::Region", RoleName]
  ServiceEndpoint:
    Value: !FindInMap [!Ref EnvironmentName, !Ref "AWS::Region", ServiceEndpoint]
  BucketEndpoint:
    Value: !FindInMap [!Ref EnvironmentName, !Ref "AWS::Region", BucketEndpoint]
