AWSTemplateFormatVersion: "2010-09-09"
Description: "Lightrail Website"

Parameters:
  EnvironmentName:
    Type: String
    Description: The Name of the Environment
    AllowedValues:
      - Dev
      - Staging
      - Production
  GroupsToGrantWebsiteReadWrite:
    Type: String
    Description: The name of the groups to grant website read write access
    AllowedPattern: "([a-zA-Z0-9+=,.@_-]+(,[a-zA-Z0-9+=,.@_-]+)*)?"

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
          -  # Allow Public Reading of all resources
            Effect: Allow
            Action:
              - s3:Get*
            Resource:
              - !Sub "arn:aws:s3:::List${Bucket}/*"
            Principal: "*"
  BucketAccessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: WebsiteBucketReadWrite
      Groups: !Split [",", GroupsToGrantWebsiteReadWrite]
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - s3:ListBucket
              - s3:GetBucket*
              - S3:GetObject*
              - s3:PutObject*
              - s3:DeleteObject*
              - s3:ListBucketMultipartUploads
            Resource:
              - !Sub "arn:aws:s3:::${Bucket}"
              - !Sub "arn:aws:s3:::${Bucket}/*"

Outputs:
  Domain:
    Description: The Website Domain for the Lightrail website
    Value: !Sub "${Bucket}.s3-website-${AWS::Region}.amazonaws.com"
  Bucket:
    Description: The Website bucket for the Lightrail website
    Value: !Ref Bucket
