AWSTemplateFormatVersion: "2010-09-09"
Description: "Lightrail Website"

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
          -  # Allow Public Reading of all resources
            Effect: Allow
            Action:
              - s3:Get*
            Resource:
              - !Sub "arn:aws:s3:::${Bucket}/*"
            Principal: "*"

Outputs:
  BucketName:
    Description: The name of the React Bucket
    Value: !Ref Bucket
  DomainName:
    Description: The Domain name to use for serving the React resources
    Value: !GetAtt Bucket.DomainName
