version: 0.1
phases:
  install:
    commands:
      - echo Build enviromment `uname -a` aws/`aws --version 2>&1` git/`git --version`
      - pip install --upgrade awscli yamllint
      - apt-get update && apt-get install -y curl rsync uuid-runtime
      - echo aws/`aws --version 2>&1`
  pre_build:
    commands:
      - bash auto.sh test
      - >
        bash -c "echo \"${ENCRYPTED_GITHUB_OAUTH_TOKEN}\"
        | base64 --decode > temp
        && mkdir ~/.github
        && aws kms decrypt --ciphertext-blob fileb://temp --query Plaintext --output text
        | base64 --decode > ~/.github/token
        && rm temp"
  build:
    commands:
      - bash auto.sh package all
  post_build:
    commands:
      - printf '{"commitId":"%s"}' $CODEBUILD_RESOLVED_SOURCE_VERSION > build.json
artifacts:
  files:
    - '**/*'
  base-directory: 'build'
  discard-paths: yes