version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Build enviromment `uname -a` aws/`aws --version 2>&1` python/`python --version` git/`git --version`
      - apt-get update && apt-get install -y curl rsync uuid-runtime
      - pip install --upgrade yamllint
      - export PATH=$PATH:/root/.local/bin
  pre_build:
    commands:
      - bash auto.sh test
      - >
        bash -c "echo \"${ENCRYPTED_GITHUB_OAUTH_TOKEN}\"
        | base64 --decode > temp
        && mkdir ~/.github
        && aws kms decrypt --ciphertext-blob fileb://temp --query Plaintext --output text
        | base64 --decode > ~/.github/token
        && rm temp"
  build:
    commands:
      - bash auto.sh package all
  post_build:
    commands:
      - printf '{"commitId":"%s"}' $CODEBUILD_RESOLVED_SOURCE_VERSION > build/build.json
artifacts:
  files:
    - '**/*'
  base-directory: 'build'
  discard-paths: yes
